apiVersion: v1
kind: Service
metadata:
  name: {{ include "hytale-server.fullname" . }}
  labels:
    {{- include "hytale-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (gt (len .Values.service.loadBalancerSourceRanges) 0) }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: quic
      port: {{ .Values.service.port }}
      protocol: UDP
      targetPort: quic
      {{- if and (eq .Values.service.type "NodePort") (not (eq .Values.service.nodePort nil)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "hytale-server.selectorLabels" . | nindent 4 }}
