apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - service.yaml
  - service-headless.yaml
  - statefulset.yaml

commonLabels:
  app.kubernetes.io/name: hytale-server
