apiVersion: v1
kind: Service
metadata:
  name: hytale-server-headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: quic
      port: 5520
      protocol: UDP
      targetPort: quic
  selector:
    app.kubernetes.io/name: hytale-server
