apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hytale-server
spec:
  serviceName: hytale-server-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hytale-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hytale-server
    spec:
      serviceAccountName: hytale-server
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 120
      containers:
        - name: hytale-server
          image: hybrowse/hytale-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: quic
              containerPort: 5520
              protocol: UDP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          env:
            - name: HYTALE_BIND
              value: "0.0.0.0:5520"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: data
          emptyDir: {}
        - name: tmp
          emptyDir:
            medium: Memory
