apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hytale-server
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: hytale-server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: UDP
          port: 5520
  egress:
    - {}
